# ============================================
# NECHE CODING AGENT - Reporter
# ============================================
# Generates reports of everything the agent
# did, found and fixed

import os
from datetime import datetime
from config import REPORT_FILE

def generate_report(scan_results, fixes_made=[]):
    """Generate a full report of scan and fixes"""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total_issues = sum(r['issue_count'] for r in scan_results)
    total_files = len(scan_results)
    clean_files = len([r for r in scan_results if r['issue_count'] == 0])
    
    report = f"""
╔══════════════════════════════════════════════╗
║              VULCAN  REPORT                 ║
║              {timestamp}              
╚══════════════════════════════════════════════╝

📊 SUMMARY
─────────────────────────────────────────────
  Total Files Scanned  : {total_files}
  Clean Files          : {clean_files}
  Files With Issues    : {total_files - clean_files}
  Total Issues Found   : {total_issues}
  Total Fixes Made     : {len(fixes_made)}

📁 FILE BREAKDOWN
─────────────────────────────────────────────
"""

    for result in scan_results:
        filename = os.path.basename(result['file'])
        count = result['issue_count']
        status = "✅ Clean" if count == 0 else f"⚠️  {count} issue(s)"
        report += f"  {status} — {filename}\n"
        
        for issue in result['issues']:
            severity_icon = {
                'high': '🔴',
                'medium': '🟡', 
                'low': '🟢'
            }.get(issue['severity'], '⚪')
            report += f"      {severity_icon} Line {issue['line']}: {issue['message']}\n"

    if fixes_made:
        report += f"""
🔧 FIXES APPLIED
─────────────────────────────────────────────
"""
        for fix in fixes_made:
            report += f"  ✅ Fixed: {fix}\n"

    report += f"""
─────────────────────────────────────────────
Generated by VULCAN — The AI That Builds, Fixes & Deploys
@nechecodes
"""

    # Save to file
    with open(REPORT_FILE, 'w', encoding='utf-8') as f:
        f.write(report)
    
    # Also print to terminal
    print(report)
    
    return report

def quick_summary(scan_results):
    """Print a quick one-line summary"""
    total_issues = sum(r['issue_count'] for r in scan_results)
    total_files = len(scan_results)
    
    if total_issues == 0:
        print(f"✅ All {total_files} files are clean!")
    else:
        print(f"⚠️  Found {total_issues} issues across {total_files} files — run fix to resolve")